### ISSUE TITLE
看了之后小小的感受

### ISSUE THREAD

**Issue by AlchemyDing** [youzhengjie9/cloud-mall#1]
开发者你好，我也是从学校里毕业出来不久的，看了这个电商微服务，感觉功能实现的很多，后端技术架构也是目前流行的。要是能够把前端代码和后端分开就好了，可以使用vue

**Comment by youzhengjie9** [comment]
> 开发者你好，我也是从学校里毕业出来不久的，看了这个电商微服务，感觉功能实现的很多，后端技术架构也是目前流行的。要是能够把前端代码和后端分开就好了，可以使用vue

谢谢您的意见，我知道现在是前后端分离的时代，由于我前端VUE不是很会，所以不敢用在项目上，我主攻方向是后端，不过有机会我也会去学习前端框架，争取把这个项目改造成符合时代趋势的前后端分离项目，再次表示感谢
